### ISSUE TITLE
Cannot add attachment when chat is shown in WebView

### ISSUE THREAD

**Issue by SzymonGrochowiak** [livechat/chat-window-android#24]
Hi, I have used `ChatWindowView` by putting it in an XML view. When I receive chat uri, I am redirecting it to WebView in my application using `handleUri(uri: Uri?)` method.

Here is my WebView configuration:
```
with(chatWebView.settings) {
    setAppCachePath(cacheDir.path)
    setAppCacheEnabled(true)
    cacheMode = WebSettings.LOAD_DEFAULT
    domStorageEnabled = true
    javaScriptEnabled = true
}
chatWebView.webChromeClient = WebChromeClient()
```

I have implemented also onStartFilePickerActivity method for the chat listener:
```
override fun onStartFilePickerActivity(intent: Intent?, requestCode: Int) {
        startActivityForResult(intent, requestCode)
}
```

Chat works correctly, but the attachment button is grayed out, and there is no action after I click on it.

**Comment by nomyzs** [comment]
Hey Szymon!

So, from what I learned, the attachment icon is disabled (hidden or grayed out) when chat hasn't been started yet (client hasn't sent his first message).

Have you noticed that? Otherwise, I don't think attachment icon visibility has anything to do with how you decided to implement this chat. However, if this is still a problem, please let me know, I will try to dig deeper. Any tips on reproducing that would be welcomed :)

**Comment by SzymonGrochowiak** [comment]
Hi, nomyzs. Thank you for your response. I have updated the live chat library to v2.1.2 and attachments seem to work fine. I am closing this issue.
