### ISSUE TITLE
Issue Loading Chat

### ISSUE THREAD

**Issue by Mastersam07** [livechat/chat-window-android#48]
I am trying to integrate the android chat widget in my android app. I keep getting the error below on my debug console.

```
I/ChatWindowView(19296): onConsoleMessageERROR Uncaught TypeError: undefined is not a function
I/chromium(19296): [INFO:CONSOLE(1)] "Uncaught TypeError: undefined is not a function", source: https://cdn.livechatinc.com/widget/static/js/iframe.eecfb93e.chunk.js (1)
```

Attached below are screenshots of the chat window initialized, error when I try to type and send a message, debug console showing the error in that order.

![Screenshot_1598438099](https://user-images.githubusercontent.com/31275429/91294778-e72a5d00-e74e-11ea-83f0-34145d3e0c0a.png)
![Screenshot_1598438109](https://user-images.githubusercontent.com/31275429/91294800-ee516b00-e74e-11ea-9cc1-ae8e2b0e05fb.png)
![Screenshot (514)](https://user-images.githubusercontent.com/31275429/91294824-f6110f80-e74e-11ea-8f6f-75a4ca367f03.png)

**Comment by Mastersam07** [comment]
I'll close this issue as I found a workaround.

**Comment by MichaelHackett** [comment]
@Mastersam07: Please share your workaround. We're seeing the same issue.

**Comment by Mastersam07** [comment]
Okay, Let me ask these questions. Are you on an emulator? Are you using flutter or native java?

**Comment by SzymonGrochowiak** [comment]
@Mastersam07 I am facing the same problem:
```I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: undefined is not a function", source: https://cdn.livechatinc.com/widget/static/js/iframe.ea2729da.chunk.js (1)```
Testing on emulator. I use Kotlin.

**Comment by Mastersam07** [comment]
The issue seems to be particular with emulators. I tested on an actual device and everything works well.

**Comment by SzymonGrochowiak** [comment]
Ok, I will try to test with some real device then. Thank you.

**Comment by Mastersam07** [comment]
👍

**Comment by MichaelHackett** [comment]
@Mastersam07: It was a while ago now, but I'm usually working on emulators, so that is likely the case. If/when I come back to that feature, I will keep the emulator issue in mind and get QA to test on physical devices. Thanks!

Still, I remain curious as to the cause. I can't think of another case where an emulator has behaved differently than a device (when there's no hardware feature being accessed), except when there's a race condition being created, or an unsupported function is being used.
