### ISSUE TITLE
External links are not working

### ISSUE THREAD

**Issue by DzakobG** [livechat/chat-window-android#61]
External links do not open on the mobile app (iOS and Android). Clicking on the link does not transfer to an external page and does not open a pdf document. The problem does not appear on the web chat. A short video of the problem in the attachment.

https://user-images.githubusercontent.com/84912688/119830955-0c761280-befd-11eb-89a9-7898de721eaa.mp4

**Comment by nomyzs** [comment]
Hello @DzakobG !

I was able to check your link configuration and it seems fine. 
I suspect this might be due to your android integration. Could you check if
1. you specified `ChatWindowEventsListener` and
2. your `handleUri(Uri uri)` method returns `false`? Also you could handle Uri by yourself here and open proper action when you detect specific link and return `true`.
Running chat window with your licence in the example opens pdf correctly. Here is the video:

https://user-images.githubusercontent.com/3172803/120316788-15d8f380-c2de-11eb-8389-d6b0fff28cf9.mov

Please let me know if that helps. Otherwise, your integration details could be helpful here. Feel free to also reach me via email: s.jarosz@livechat.com in case you don't want to share some information publicly :)

All best! :)

**Comment by nomyzs** [comment]
I just noticing that it is working fine now in your app. Not taking any credit, but I do hope I helped ;)
